### ISSUE TITLE
Compatibility with Node v0.5.3

### ISSUE THREAD

**Issue by rxbynerd** [cjoudrey/wobot#10]
Hey,

I'm attempting to use an `https.method` call in my code (to get Airbrake exception information), which doesn't work with v0.4.6 of node, and requires v0.5.3

However, wobot v0.3.0 explicitly states it needs < 0.5.0, is there a gigantic dragon I will need to slay in order to get the thing to work?

Thanks,
Luke

**Comment by cjoudrey** [comment]
Hey Luke,

I explicitly put `< 0.5.0` as I have not yet tested Wobot on 0.5.x.

For now, I would suggest cloning the repo and manually installing the dependencies.

I.e.:

```
cd your_project
git clone git@github.com:cjoudrey/wobot.git
cd wobot
npm install node-xmpp
npm install underscore
```

and require `wobot/lib/index`.

Should work.

**Comment by rxbynerd** [comment]
Ah right OK, Thanks, I'll let you know if I find any issues

**Comment by rxbynerd** [comment]
Looks to be a problem with /usr/local/lib/node_modules/node-xmpp/node_modules/node-expat/build/default/node-expat.node, non-compatible for the time being :zap:
