### ISSUE TITLE
Compatibility with Node v0.5.x

### ISSUE THREAD

**Issue by mathewpeterson** [cjoudrey/wobot#13]
Do plan on supporting node 0.5.x?

**Comment by cjoudrey** [comment]
Yeah definitely. To be honest most of the code currently runs in v0.5.

Wobot depends a lot on `node-xmpp` for communication so it's really a matter of them supporting v0.5.

**Comment by Vrtak-CZ** [comment]
New stable 0.6.0 is out. Any news?

**Comment by cjoudrey** [comment]
I'll test it tonight and update the package.json.

**Comment by cjoudrey** [comment]
I'm having some issues running wobot in `v0.6.0`. Looking into it..

Opened a ticket for `node-xmpp` as well: astro/node-xmpp#43.

**Comment by cjoudrey** [comment]
Another related dependency bug: astro/node-expat#21

**Comment by erik-megarad** [comment]
Once the dependencies merge already-created pull requests, wobot installs cleanly. I vote that you go ahead and update package.json to allow a 0.6.0 install so that it'll automatically work as soon as the dependencies are resolved.

**Comment by cjoudrey** [comment]
They also made the change backward compatible (https://github.com/jorritd/node-expat/commit/40699d0bdb16dd21960171cf756c6cf98d9ae9ed) so I'm guessing it should be released soon.

I'll update the `package.json` when I get home in a few hours.

In the meantime, you can `git clone` the repo, edit `package.json` and `npm install folder/`.

**Comment by cjoudrey** [comment]
Just released v0.3.1 with support for node v0.6.0.

Now we just need to wait for `node-xmpp`.
