### ISSUE TITLE
Add a better API for message events

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/wobot#8]
The current way of setting message callbacks isn't very friendly since you always need to validate the message before continuing:

``` javascript
bot.on('message', function(channel, from, message) {
  if (message !== '!chuck') {
    return false;
  }
  // !chuck stuff..
}));
```

In addition, `EventEmitters` don't give us the flexibility of adding `RegExp` and complex conditions to our binding.
# New API proposal
## bot.onConnect

Triggered when the bot successfully connects.

``` javascript
bot.onConnect(function() {

});
```
## bot.onMessage

Triggered by channel messages.

``` javascript
bot.onMessage('!chuck', function(channel, from, message) {

}));
```

The first argument can be either a String or a `RegExp`.

``` javascript
bot.onMessage(/^\!weather ([0-9]+)$/, function(channel, from, message, matches) {

}));
```

The result of the `.match` are returned as the 4th argument.
## bot.onPrivateMessage

Triggered by private messages.

``` javascript
bot.onPrivateMessage('!chuck', function(from, message) {

}));
```

The first argument can be either a String or a `RegExp`.

``` javascript
bot.onPrivateMessage(/^\!weather ([0-9]+)$/, function(from, message, matches) {

}));
```

The result of the `.match` are returned as the 4th argument.
## bot.onPing

Triggered whenever the bot pings HipChat (roughly every 30 seconds).

``` javascript
bot.onPing(function() {

});
```
## bot.onError

Triggered whenever a XMPP error occurs.
This will automatically trigger `onDisconnect`.

``` javascript
bot.onError(function(errMessage, stanza) {

});
```
## bot.onDisconnect

Triggered whenever the bot disconnects.

``` javascript
bot.onDisconnect(function() {

});
```
## bot.message(targetJid, message)

The `bot.pm` will be removed and combined into `bot.message`.

The function will auto-detect the target-type and take the appropriate action of sending the message to the channel or via private message to the user.
## bot.reply(message)

Within a callback you can use `this.reply` which will send the message to either the room or the person depending on the type of event.

For instance, if the callback is triggered by `onMessage`, `this.reply('test')` will send the message to the room.

If the callback is triggered by `onPrivate`, `this.reply('test')` will send the message to the person.

**Comment by mishan** [comment]
I like the idea a lot since this is my primary use case for the handlers. Having a universal callback function prototype would be key, though, to maximize code reuse for plugin developers.

**Comment by cjoudrey** [comment]
@mishan I agree, but I think we can write a universal wrapper on top of this new API quite easily afterwards.

The first problem is to solve the EventEmitter problem (i.e. not being able to use `RegExp`).
